name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install deps
        run: poetry install

      - name: Format check
        run: |
          poetry run isort --check .
          poetry run black --check .

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sqlite
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Poetry
        run: pip install poetry

      - name: Install deps
        run: poetry install

      - name: Test
        run: poetry run pytest tests/

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Poetry
        run: pip install poetry

      - name: Install deps
        run: poetry install

      - name: Test
        run: poetry run pytest tests/
